/*
 *  This file is part of RawTherapee.
 *
 *  Copyright (c) 2004-2010 Gabor Horvath <hgabor@rawtherapee.com>
 *
 *  RawTherapee is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  RawTherapee is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with RawTherapee.  If not, see <https://www.gnu.org/licenses/>.
 */
#include "refreshmap.h"
#include "procevents.h"







// Aligned so the first entry starts on line 30.
int refreshmap[rtengine::NUMOFEVENTS] = {
    ALL,              // EvPhotoLoaded,
    ALL,              // EvProfileLoaded,
    ALL,              // EvProfileChanged,
    ALL,              // EvHistoryBrowsed,
    RGBCURVE,         // EvBrightness,
    RGBCURVE,         // EvContrast,
    RGBCURVE,         // EvBlack,
    RGBCURVE,         // EvExpComp,
    RGBCURVE,         // EvHLCompr,
    RGBCURVE,         // EvSHCompr,
    RGBCURVE,         // EvToneCurve1,
    AUTOEXP,          // EvAutoExp,
    AUTOEXP,          // EvClip,
    LUMINANCECURVE,   // EvLBrightness,
    LUMINANCECURVE,   // EvLContrast,
    LUMINANCECURVE,   // EvLBlack,
    LUMINANCECURVE,   // EvLHLCompr,
    LUMINANCECURVE,   // EvLSHCompr,
    LUMINANCECURVE,   // EvLLCurve,
    SHARPENING,       // EvShrEnabled,
    SHARPENING,       // EvShrRadius,
    SHARPENING,       // EvShrAmount,
    SHARPENING,       // EvShrThresh,
    SHARPENING,       // EvShrEdgeOnly,
    SHARPENING,       // EvShrEdgeRadius,
    SHARPENING,       // EvShrEdgeTolerance,
    SHARPENING,       // EvShrHaloControl,
    SHARPENING,       // EvShrHaloAmount,
    SHARPENING,       // EvShrMethod,
    SHARPENING,       // EvShrDRadius,
    SHARPENING,       // EvShrDAmount,
    SHARPENING,       // EvShrDDamping,
    SHARPENING,       // EvShrDIterations,
    TRANSFORM,        // EvLCPUseDist,
    DARKFRAME,        // EvLCPUseVign,
    TRANSFORM,        // EvLCPUseCA,
    M_VOID,           // EvFixedExp
    ALLNORAW,         // EvWBMethod,
    ALLNORAW,         // EvWBTemp,
    ALLNORAW,         // EvWBGreen,
    RGBCURVE,         // EvToneCurveMode1,
    RGBCURVE,         // EvToneCurve2,
    RGBCURVE,         // EvToneCurveMode2,
    0,                // EvLDNRadius: obsolete,
    0,                // EvLDNEdgeTolerance: obsolete,
    0,                // EvCDNEnabled:obsolete,
    0,                // free entry
    RGBCURVE | M_AUTOEXP, // EvDCPToneCurve,
    ALLNORAW,         // EvDCPIlluminant,
    RETINEX,          // EvSHEnabled,
    RGBCURVE,         // EvSHHighlights,
    RGBCURVE,         // EvSHShadows,
    RGBCURVE,         // EvSHHLTonalW,
    RGBCURVE,         // EvSHSHTonalW,
    RGBCURVE,         // EvSHLContrast,
    RETINEX,          // EvSHRadius,
    ALLNORAW,         // EvCTRotate,
    ALLNORAW,         // EvCTHFlip,
    ALLNORAW,         // EvCTVFlip,
    TRANSFORM,        // EvROTDegree,
    TRANSFORM,        // EvTransAutoFill,
    TRANSFORM,        // EvDISTAmount,
    ALL,              // EvBookmarkSelected,
    CROP,             // EvCrop,
    TRANSFORM,        // EvCACorr,
    ALLNORAW,         // EvHREnabled,
    ALLNORAW,         // EvHRAmount,
    ALLNORAW,         // EvHRMethod,
    DEMOSAIC,         // EvWProfile,
    OUTPUTPROFILE,    // EvOProfile,
    ALLNORAW,         // EvIProfile,
    TRANSFORM,        // EvVignettingAmount,
    RGBCURVE,         // EvChMixer,
    RESIZE,           // EvResizeScale,
    RESIZE,           // EvResizeMethod,
    EXIF,             // EvExif,
    IPTC,             // EvIPTC
    RESIZE,           // EvResizeSpec,
    RESIZE,           // EvResizeWidth
    RESIZE,           // EvResizeHeight
    RESIZE,           // EvResizeEnabled
    ALL,              // EvProfileChangeNotification
    RETINEX,          // EvShrHighQuality
    TRANSFORM,        // EvPerspCorr
    DARKFRAME,        // EvLCPFile
    RGBCURVE,         // EvRGBrCurveLumamode
    IMPULSEDENOISE,   // EvIDNEnabled,
    IMPULSEDENOISE,   // EvIDNThresh,
    ALLNORAW,         // EvDPDNEnabled,
    ALLNORAW,         // EvDPDNLuma,
    ALLNORAW,         // EvDPDNChroma,
    ALLNORAW,         // EvDPDNGamma,
    ALLNORAW,         // EvDirPyrEqualizer,
    ALLNORAW,         // EvDirPyrEqlEnabled,
    LUMINANCECURVE,   // EvLSaturation,
    LUMINANCECURVE,   // EvLaCurve,
    LUMINANCECURVE,   // EvLbCurve,
    DEMOSAIC,         // EvDemosaicMethod
    DARKFRAME,        // EvPreProcessHotPixel
    RGBCURVE,         // EvSaturation,
    RGBCURVE,         // EvHSVEqualizerH,
    RGBCURVE,         // EvHSVEqualizerS,
    RGBCURVE,         // EvHSVEqualizerV,
    RGBCURVE,         // EvHSVEqEnabled,
    DEFRINGE,         // EvDefringeEnabled,
    DEFRINGE,         // EvDefringeRadius,
    DEFRINGE,         // EvDefringeThreshold,
    RGBCURVE,         // EvHLComprThreshold,
    RESIZE,           // EvResizeBoundingBox
    RESIZE,           // EvResizeAppliesTo
    LUMINANCECURVE,   // EvCBAvoidClip,
    LUMINANCECURVE,   // EvCBSatLimiter,
    LUMINANCECURVE,   // EvCBSatLimit,
    DEMOSAIC,         // EvDemosaicDCBIter
    ALLNORAW,         // EvDemosaicFalseColorIter
    DEMOSAIC,         // EvDemosaicDCBEnhanced
    DARKFRAME,        // EvPreProcessCARed
    DARKFRAME,        // EvPreProcessCABlue
    DARKFRAME,        // EvPreProcessLineDenoise
    DARKFRAME,        // EvPreProcessGEquilThresh
    DARKFRAME,        // EvPreProcessAutoCA
    DARKFRAME,        // EvPreProcessAutoDF
    DARKFRAME,        // EvPreProcessDFFile
    DARKFRAME,        // EvPreProcessExpCorrLinear
    0,                // --unused--
    FLATFIELD,        // EvFlatFieldFile,
    FLATFIELD,        // EvFlatFieldAutoSelect,
    FLATFIELD,        // EvFlatFieldBlurRadius,
    FLATFIELD,        // EvFlatFieldBlurType,
    TRANSFORM,        // EvAutoDIST,
    ALLNORAW,         // EvDPDNLumCurve,
    ALLNORAW,         // EvDPDNChromCurve,
    GAMMA,            // EvGAMMA
    GAMMA,            // EvGAMPOS
    GAMMA,            // EvGAMFREE
    GAMMA,            // EvSLPOS
    DARKFRAME,        // EvPreProcessExpBlackzero
    DARKFRAME,        // EvPreProcessExpBlackone
    DARKFRAME,        // EvPreProcessExpBlacktwo
    DARKFRAME,        // EvPreProcessExpBlackthree
    DARKFRAME,        // EvPreProcessExptwoGreen
    SHARPENING,       // EvSharpenEdgePasses
    SHARPENING,       // EvSharpenEdgeStrength
    SHARPENING,       // EvSharpenMicroStrength
    SHARPENING,       // EvSharpenMicroUniformity
    SHARPENING,       // EvSharpenEdgeEnabled
    SHARPENING,       // EvSharpenEdgeThreechannels
    SHARPENING,       // EvSharpenMicroEnabled
    SHARPENING,       // EvSharpenMicroMatrix
    DEMOSAIC,         // EvDemosaicALLEnhanced Disabled but not removed for now, may be reintroduced some day
    RGBCURVE,         // EvVibranceEnabled
    RGBCURVE,         // EvVibrancePastels
    RGBCURVE,         // EvVibranceSaturated
    RGBCURVE,         // EvVibranceProtectSkins
    RGBCURVE,         // EvVibranceAvoidColorShift
    RGBCURVE,         // EvVibrancePastSatTog
    RGBCURVE,         // EvVibrancePastSatThreshold
    SHARPENING,       // EvEPDStrength
    SHARPENING,       // EvEPDEdgeStopping
    SHARPENING,       // EvEPDScale
    SHARPENING,       // EvEPDReweightingIterates
    SHARPENING,       // EvEPDEnabled
    RGBCURVE,         // EvRGBrCurve
    RGBCURVE,         // EvRGBgCurve
    RGBCURVE,         // EvRGBbCurve
    RGBCURVE,         // EvNeutralExp
    DEMOSAIC | M_PREPROC, // EvDemosaicMethodPreProc
    LUMINANCECURVE,   // EvLCCurve
    LUMINANCECURVE,   // EvLCHCurve
    RGBCURVE,         // EvVibranceSkinTonesCurve
    LUMINANCECURVE,   // EvLLCCurve
    LUMINANCECURVE,   // EvLLCredsk
    ALLNORAW,         // EvDPDNLdetail
    ALLNORAW,         // EvCATEnabled
    LUMINANCECURVE,   // EvCATDegree
    LUMINANCECURVE,   // EvCATMethodsur
    LUMINANCECURVE,   // EvCATAdapscen
    LUMINANCECURVE,   // EvCATAdapLum
    LUMINANCECURVE,   // EvCATMethodWB
    LUMINANCECURVE,   // EvCATJLight
    LUMINANCECURVE,   // EvCATChroma
    LUMINANCECURVE,   // EvCATAutoDegree
    LUMINANCECURVE,   // EvCATContrast
    LUMINANCECURVE,   // EvCATSurr
    LUMINANCECURVE,   // EvCATgamut
    LUMINANCECURVE,   // EvCATmethodalg
    LUMINANCECURVE,   // EvCATRstpro
    LUMINANCECURVE,   // EvCATQbright
    LUMINANCECURVE,   // EvCATQContrast
    LUMINANCECURVE,   // EvCATSChroma
    LUMINANCECURVE,   // EvCATMchroma
    LUMINANCECURVE,   // EvCAThue
    LUMINANCECURVE,   // EvCATcurve1
    LUMINANCECURVE,   // EvCATcurve2
    LUMINANCECURVE,   // EvCATcurvemode1
    LUMINANCECURVE,   // EvCATcurvemode2
    LUMINANCECURVE,   // EvCATcurve3
    LUMINANCECURVE,   // EvCATcurvemode3
    LUMINANCECURVE,   // EvCATdatacie
    LUMINANCECURVE,   // EvCATtonecie
    ALLNORAW,         // EvDPDNbluechro
    ALLNORAW,         // EvDPDNperform
    ALLNORAW,         // EvDPDNmet
    DEMOSAIC,         // EvDemosaicLMMSEIter
    LUMINANCECURVE,   // EvCATbadpix
    LUMINANCECURVE,   // EvCATAutoadap
    DEFRINGE,         // EvPFCurve
    ALLNORAW,         // EvWBequal
    ALLNORAW,         // EvWBequalbo
    TRANSFORM,        // EvGradientDegree
    TRANSFORM,        // EvGradientEnabled
    TRANSFORM,        // EvPCVignetteStrength
    TRANSFORM,        // EvPCVignetteEnabled
    RGBCURVE,         // EvBWChmixEnabled
    RGBCURVE,         // EvBWred
    RGBCURVE,         // EvBWgreen
    RGBCURVE,         // EvBWblue
    RGBCURVE,         // EvBWredgam
    RGBCURVE,         // EvBWgreengam
    RGBCURVE,         // EvBWbluegam
    RGBCURVE,         // EvBWfilter
    RGBCURVE,         // EvBWsetting
    RGBCURVE,         // EvBWoran
    RGBCURVE,         // EvBWyell
    RGBCURVE,         // EvBWcyan
    RGBCURVE,         // EvBWmag
    RGBCURVE,         // EvBpur
    RGBCURVE,         // EvBWLuminanceEqual
    RGBCURVE,         // EvBWChmixEnabledLm
    RGBCURVE,         // EvBWmethod
    RGBCURVE,         // EvBWBeforeCurve
    RGBCURVE,         // EvBWBeforeCurveMode
    RGBCURVE,         // EvBWAfterCurve
    RGBCURVE,         // EvBWAfterCurveMode
    RGBCURVE,         // EvAutoch
    0,                // --unused--
    RGBCURVE,         // EvNeutralBW
    TRANSFORM,        // EvGradientFeather
    TRANSFORM,        // EvGradientStrength
    TRANSFORM,        // EvGradientCenter
    TRANSFORM,        // EvPCVignetteFeather
    TRANSFORM,        // EvPCVignetteRoundness
    TRANSFORM,        // EvVignettingRadius,
    TRANSFORM,        // EvVignettingStrength
    TRANSFORM,        // EvVignettingCenter
    LUMINANCECURVE,   // EvLCLCurve
    LUMINANCECURVE,   // EvLLHCurve
    LUMINANCECURVE,   // EvLHHCurve
    ALLNORAW,         // EvDirPyrEqualizerThreshold
    ALLNORAW,         // EvDPDNenhance
    RGBCURVE,         // EvBWMethodalg
    ALLNORAW,         // EvDirPyrEqualizerSkin
    ALLNORAW,         // EvDirPyrEqlgamutlab
    ALLNORAW,         // EvDirPyrEqualizerHueskin
    ALLNORAW,         // EvDPDNmedian
    ALLNORAW,         // EvDPDNmedmet
    RGBCURVE,         // EvColorToningEnabled
    RGBCURVE,         // EvColorToningColor
    RGBCURVE,         // EvColorToningOpacity
    RGBCURVE,         // EvColorToningCLCurve
    RGBCURVE,         // EvColorToningMethod
    RGBCURVE,         // EvColorToningLLCurve
    RGBCURVE,         // EvColorToningredlow
    RGBCURVE,         // EvColorToninggreenlow
    RGBCURVE,         // EvColorToningbluelow
    RGBCURVE,         // EvColorToningredmed
    RGBCURVE,         // EvColorToninggreenmed
    RGBCURVE,         // EvColorToningbluemed
    RGBCURVE,         // EvColorToningredhigh
    RGBCURVE,         // EvColorToninggreenhigh
    RGBCURVE,         // EvColorToningbluehigh
    RGBCURVE,         // EvColorToningbalance
    RGBCURVE,         // EvColorToningNeutral
    RGBCURVE,         // EvColorToningsatlow
    RGBCURVE,         // EvColorToningsathigh
    RGBCURVE,         // EvColorToningTwocolor
    RGBCURVE,         // EvColorToningNeutralcur
    RGBCURVE,         // EvColorToningLumamode
    RGBCURVE,         // EvColorToningShadows
    RGBCURVE,         // EvColorToningHighights
    RGBCURVE,         // EvColorToningSatProtection
    RGBCURVE,         // EvColorToningSatThreshold
    RGBCURVE,         // EvColorToningStrength
    RGBCURVE,         // EvColorToningautosat
    ALLNORAW,         // EvDPDNmetmed
    ALLNORAW,         // EvDPDNrgbmet
    ALLNORAW,         // EvDPDNpasses
    FLATFIELD,        // EvFlatFieldClipControl
    FLATFIELD,        // EvFlatFieldAutoClipControl
    DARKFRAME,        // EvPreProcessExpBlackRed
    DARKFRAME,        // EvPreProcessExpBlackGreen
    DARKFRAME,        // EvPreProcessExpBlackBlue
    RGBCURVE,         // EvFilmSimulationEnabled
    RGBCURVE,         // EvFilmSimulationStrength
    RGBCURVE,         // EvFilmSimulationFilename
    ALLNORAW,         // EvDPDNLCurve
    ALLNORAW,         // EvDPDNsmet
    DARKFRAME,        // EvPreProcessDeadPixel
    ALLNORAW,         // EvDPDNCCCurve
    ALLNORAW,         // EvDPDNautochroma
    ALLNORAW,         // EvDPDNLmet
    ALLNORAW,         // EvDPDNCmet
    ALLNORAW,         // EvDPDNC2met
    DIRPYREQUALIZER,  // EvWavelet
    DIRPYREQUALIZER,  // EvEnabled
    DIRPYREQUALIZER,  // EvWavLmethod
    DIRPYREQUALIZER,  // EvWavCLmethod
    DIRPYREQUALIZER,  // EvWavDirmethod
    DIRPYREQUALIZER,  // EvWavtiles
    DIRPYREQUALIZER,  // EvWavsky
    DIRPYREQUALIZER,  // EvWavthres
    DIRPYREQUALIZER,  // EvWavthr
    DIRPYREQUALIZER,  // EvWavchroma
    DIRPYREQUALIZER,  // EvWavmedian
    DIRPYREQUALIZER,  // EvWavunif
    DIRPYREQUALIZER,  // EvWavSkin
    DIRPYREQUALIZER,  // EvWavHueSkin
    DIRPYREQUALIZER,  // EvWavThreshold
    DIRPYREQUALIZER,  // EvWavlhl
    DIRPYREQUALIZER,  // EvWavbhl
    DIRPYREQUALIZER,  // EvWavThresHold2
    DIRPYREQUALIZER,  // EvWavavoid
    DIRPYREQUALIZER,  // EvWavCCCurve
    DIRPYREQUALIZER,  // EvWavpast
    DIRPYREQUALIZER,  // EvWavsat
    DIRPYREQUALIZER,  // EvWavCHmet
    DIRPYREQUALIZER,  // EvWavHSmet
    DIRPYREQUALIZER,  // EvWavchro
    DIRPYREQUALIZER,  // EvWavColor
    DIRPYREQUALIZER,  // EvWavOpac
    DIRPYREQUALIZER,  // EvWavsup
    DIRPYREQUALIZER,  // EvWavTilesmet
    DIRPYREQUALIZER,  // EvWavrescon
    DIRPYREQUALIZER,  // EvWavreschro
    DIRPYREQUALIZER,  // EvWavresconH
    DIRPYREQUALIZER,  // EvWavthrH
    DIRPYREQUALIZER,  // EvWavHueskin2
    DIRPYREQUALIZER,  // EvWavedgrad
    DIRPYREQUALIZER,  // EvWavedgval
    DIRPYREQUALIZER,  // EvWavStrngth
    DIRPYREQUALIZER,  // EvWavdaubcoeffmet
    DIRPYREQUALIZER,  // EvWavedgreinf
    DIRPYREQUALIZER,  // EvWaveletch
    DIRPYREQUALIZER,  // EvWavCHSLmet
    DIRPYREQUALIZER,  // EvWavedgcont
    DIRPYREQUALIZER,  // EvWavEDmet
    DIRPYREQUALIZER,  // EvWavlev0nois
    DIRPYREQUALIZER,  // EvWavlev1nois
    DIRPYREQUALIZER,  // EvWavlev2nois
    DIRPYREQUALIZER,  // EvWavmedianlev
    DIRPYREQUALIZER,  // EvWavHHCurve
    DIRPYREQUALIZER,  // EvWavBackmet
    DIRPYREQUALIZER,  // EvWavedgedetect
    DIRPYREQUALIZER,  // EvWavlipst
    DIRPYREQUALIZER,  // EvWavedgedetectthr
    DIRPYREQUALIZER,  // EvWavedgedetectthr2
    DIRPYREQUALIZER,  // EvWavlinkedg
    DIRPYREQUALIZER,  // EvWavCHCurve
    DARKFRAME,        // EvPreProcessHotDeadThresh
    SHARPENING,       // EvEPDgamma
    DIRPYREQUALIZER,  // EvWavtmr
    DIRPYREQUALIZER,  // EvWavTMmet
    DIRPYREQUALIZER,  // EvWavtmrs
    DIRPYREQUALIZER,  // EvWavbalance
    DIRPYREQUALIZER,  // EvWaviter
    DIRPYREQUALIZER,  // EvWavgamma
    DIRPYREQUALIZER,  // EvWavCLCurve
    DIRPYREQUALIZER,  // EvWavopacity
    DIRPYREQUALIZER,  // EvWavBAmet
    DIRPYREQUALIZER,  // EvWavopacityWL
    RESIZE,           // EvPrShrEnabled
    RESIZE,           // EvPrShrRadius
    RESIZE,           // EvPrShrAmount
    RESIZE,           // EvPrShrThresh
    RESIZE,           // EvPrShrEdgeOnly
    RESIZE,           // EvPrShrEdgeRadius=375,
    RESIZE,           // EvPrShrEdgeTolerance=376,
    RESIZE,           // EvPrShrHaloControl=377,
    RESIZE,           // EvPrShrHaloAmount=378,
    RESIZE,           // EvPrShrMethod=379,
    RESIZE,           // EvPrShrDRadius=380,
    RESIZE,           // EvPrShrDAmount=381,
    RESIZE,           // EvPrShrDDamping=382,
    RESIZE,           // EvPrShrDIterations=383,
    DIRPYREQUALIZER,  // EvWavcbenab
    DIRPYREQUALIZER,  // EvWavgreenhigh
    DIRPYREQUALIZER,  // EvWavbluehigh
    DIRPYREQUALIZER,  // EvWavgreenmed
    DIRPYREQUALIZER,  // EvWavbluemed
    DIRPYREQUALIZER,  // EvWavgreenlow
    DIRPYREQUALIZER,  // EvWavbluelow
    DIRPYREQUALIZER,  // EvWavNeutral
    RGBCURVE | M_AUTOEXP, // EvDCPApplyLookTable,
    RGBCURVE | M_AUTOEXP, // EvDCPApplyBaselineExposureOffset,
    ALLNORAW,         // EvDCPApplyHueSatMap
    DIRPYREQUALIZER,  // EvWavenacont
    DIRPYREQUALIZER,  // EvWavenachrom
    DIRPYREQUALIZER,  // EvWavenaedge
    DIRPYREQUALIZER,  // EvWavenares
    DIRPYREQUALIZER,  // EvWavenafin
    DIRPYREQUALIZER,  // EvWavenatoning
    DIRPYREQUALIZER,  // EvWavenanoise
    DIRPYREQUALIZER,  // EvWavedgesensi
    DIRPYREQUALIZER,  // EvWavedgeampli
    DIRPYREQUALIZER,  // EvWavlev3nois
    DIRPYREQUALIZER,  // EvWavNPmet
    DEMOSAIC,         // EvretinexMethod
    RETINEX,          // EvLneigh
    RETINEX,          // EvLgain
    RETINEX,          // EvLoffs
    RETINEX,          // EvLstr
    RETINEX,          // EvLscal
    RETINEX,          // EvLvart
    DEMOSAIC,         // EvLCDCurve
    RETINEX,          // EvRetinextransmission
    DEMOSAIC,         // EvRetinexEnabled
    RETINEX,          // EvRetinexmedianmap
    RETINEX,          // EvLlimd
    DEMOSAIC,         // Evretinexcolorspace
    DEMOSAIC,         // EvLCDHCurve
    DEMOSAIC,         // Evretinexgamma
    DEMOSAIC,         // EvLgam
    DEMOSAIC,         // EvLslope
    RETINEX,          // EvLhighl
    0,                // --unused--
    DEMOSAIC,         // EvRetinexlhcurve
    OUTPUTPROFILE,    // EvOIntent
    MONITORTRANSFORM, // EvMonitorTransform: no history message
    RETINEX,          // EvLiter
    RETINEX,          // EvLgrad
    RETINEX,          // EvLgrads
    RETINEX,          // EvLhighlights
    RETINEX,          // EvLh_tonalwidth
    RETINEX,          // EvLshadows
    RETINEX,          // EvLs_tonalwidth
    RETINEX,          // EvLradius
    RETINEX,          // EvmapMethod
    DEMOSAIC,         // EvRetinexmapcurve
    DEMOSAIC,         // EvviewMethod
    ALLNORAW,         // EvcbdlMethod
    RETINEX,          // EvRetinexgaintransmission
    RETINEX,          // EvLskal
    OUTPUTPROFILE,    // EvOBPCompens
    ALLNORAW,         // EvWBtempBias
    DARKFRAME,        // EvRawImageNum
    0,                // unused
    0,                // unused
    0,                // unused
    DEMOSAIC,         // EvPixelShiftEperIso
    0,                // unused
    0,                // unused
    DEMOSAIC,         // EvPixelshiftShowMotion
    DEMOSAIC,         // EvPixelshiftShowMotionMaskOnly
    0,                // unused
    0,                // unused
    0,                // unused
    DEMOSAIC,         // EvPixelShiftNonGreenCross
    0,                // unused
    0,                // unused
    0,                // unused
    0,                // unused
    DEMOSAIC,         // EvPixelShiftGreen
    0,                // unused
    DEMOSAIC,         // EvPixelShiftBlur
    DEMOSAIC,         // EvPixelShiftSigma
    0,                // unused
    0,                // unused
    DEMOSAIC,         // EvPixelShiftHoleFill
    DEMOSAIC,         // EvPixelShiftMedian
    0,                // unused
    DEMOSAIC,         // EvPixelShiftMotionMethod
    DEMOSAIC,         // EvPixelShiftSmooth
    DEMOSAIC,         // EvPixelShiftLmmse
    DEMOSAIC,         // EvPixelShiftEqualBright
    DEMOSAIC,         // EvPixelShiftEqualBrightChannel
    LUMINANCECURVE,   // EvCATtempout
    LUMINANCECURVE,   // EvCATgreenout
    LUMINANCECURVE,   // EvCATybout
    LUMINANCECURVE,   // EvCATDegreeout
    LUMINANCECURVE,   // EvCATAutoDegreeout
    LUMINANCECURVE,   // EvCATtempsc
    LUMINANCECURVE,   // EvCATgreensc
    LUMINANCECURVE,   // EvCATybscen
    LUMINANCECURVE,   // EvCATAutoyb
    DARKFRAME,        // EvLensCorrMode
    DARKFRAME,        // EvLensCorrLensfunCamera
    DARKFRAME,        // EvLensCorrLensfunLens
    ALLNORAW,         // EvTMFattalEnabled
    HDR,              // EvTMFattalThreshold
    HDR,              // EvTMFattalAmount
    ALLNORAW,         // EvWBEnabled
    RGBCURVE,         // EvRGBEnabled
    LUMINANCECURVE,   // EvLEnabled
    DEMOSAIC,         // EvPdShrEnabled
    CAPTURESHARPEN,    // EvPdShrMaskToggled
    AUTOEXP,   // EvLocallabSpotDeleted
    M_VOID,           // EvLocallabSpotSelected
    M_VOID,           // EvLocallabSpotName
    M_VOID,           // EvLocallabSpotVisibility
    AUTOEXP,   // EvLocallabSpotShape
    AUTOEXP,   // EvLocallabSpotSpotMethod
    AUTOEXP,   // EvLocallabSpotShapeMethod
    AUTOEXP,   // EvLocallabSpotLocX
    AUTOEXP,   // EvLocallabSpotLocXL
    AUTOEXP,   // EvLocallabSpotLocY
    AUTOEXP,   // EvLocallabSpotLocYT
    AUTOEXP,   // EvLocallabSpotCenter
    AUTOEXP,   // EvLocallabSpotCircrad
    AUTOEXP,   // EvLocallabSpotQualityMethod
    AUTOEXP,   // EvLocallabSpotTransit
    AUTOEXP,   // EvLocallabSpotThresh
    AUTOEXP,   // EvLocallabSpotIter
    AUTOEXP,   // EvLocallabSpotSensiexclu
    AUTOEXP,   // EvLocallabSpotStruc
    AUTOEXP,   // EvlocallabEnabled
    AUTOEXP,   // EvLocenacolor
    AUTOEXP,   // Evlocallabcurvactiv
    AUTOEXP,   // Evlocallablightness
    AUTOEXP,   // Evlocallabcontrast
    AUTOEXP,   // Evlocallabchroma
    AUTOEXP,   // Evlocallabsensi
    AUTOEXP,   // EvlocallabqualitycurveMethod
    AUTOEXP,   // Evlocallabllshape
    AUTOEXP,   // Evlocallabccshape
    AUTOEXP,   // EvlocallabLHshape
    AUTOEXP,   // EvlocallabHHshape
    AUTOEXP,   // Evlocallabinvers
    AUTOEXP,   // EvLocenaexpose
    AUTOEXP,   // Evlocallabexpcomp
    AUTOEXP,   // Evlocallabhlcompr
    AUTOEXP,   // Evlocallabhlcomprthresh
    AUTOEXP,   // Evlocallabblack
    AUTOEXP,   // Evlocallabshcompr
    AUTOEXP,   // Evlocallabwarm
    AUTOEXP,   // Evlocallabsensiex
    AUTOEXP,   // Evlocallabshapeexpos
    AUTOEXP,   // EvLocenavibrance
    AUTOEXP,   // EvlocallabSaturated
    AUTOEXP,   // EvlocallabPastels
    AUTOEXP,   // EvlocallabPastSatThreshold
    AUTOEXP,   // EvlocallabProtectSkins
    AUTOEXP,   // EvlocallabAvoidColorShift
    AUTOEXP,   // EvlocallabPastSatTog
    AUTOEXP,   // Evlocallabsensiv
    AUTOEXP,   // EvlocallabSkinTonesCurve
    AUTOEXP,   // EvLocenablur
    AUTOEXP,   // Evlocallabradius
    AUTOEXP,   // Evlocallabstrength
    AUTOEXP,   // Evlocallabsensibn
    AUTOEXP,   // EvlocallabblurMethod
    AUTOEXP,   // Evlocallabactivlum
    AUTOEXP,   // EvLocenatonemap
    AUTOEXP,   // Evlocallabstren
    AUTOEXP,   // Evlocallabgamma
    AUTOEXP,   // Evlocallabestop
    AUTOEXP,   // Evlocallabscaltm
    AUTOEXP,   // Evlocallabrewei
    AUTOEXP,   // Evlocallabsensitm
    AUTOEXP,   // EvLocenareti
    AUTOEXP,   // EvlocallabretinexMethod
    AUTOEXP,   // Evlocallabstr
    AUTOEXP,   // Evlocallabchrrt
    AUTOEXP,   // Evlocallabneigh
    AUTOEXP,   // Evlocallabvart
    AUTOEXP,   // Evlocallabsensih
    AUTOEXP,   // EvlocallabCTgainCurve
    AUTOEXP,   // Evlocallabinversret
    AUTOEXP,   // EvLocenasharp
    AUTOEXP,   // Evlocallabsharradius
    AUTOEXP,   // Evlocallabsharamount
    AUTOEXP,   // Evlocallabshardamping
    AUTOEXP,   // Evlocallabshariter
    AUTOEXP,   // Evlocallabsensis
    AUTOEXP,   // Evlocallabinverssha
    AUTOEXP,   // EvLocenacbdl
    AUTOEXP,   // EvlocallabEqualizer
    AUTOEXP,   // Evlocallabchromacbdl
    AUTOEXP,   // EvlocallabThresho
    AUTOEXP,   // Evlocallabsensicb
    AUTOEXP,   // EvLocenadenoi
    AUTOEXP,   // Evlocallabnoiselumf
    AUTOEXP,   // Evlocallabnoiselumc
    AUTOEXP,   // Evlocallabnoiselumdetail
    AUTOEXP,   // Evlocallabnoiselequal
    AUTOEXP,   // Evlocallabnoisechrof
    AUTOEXP,   // Evlocallabnoisechroc
    AUTOEXP,   // Evlocallabnoisechrodetail
    AUTOEXP,   // Evlocallabadjblur
    AUTOEXP,   // Evlocallabbilateral
    AUTOEXP,   // Evlocallabsensiden
    AUTOEXP,   // Evlocallabavoid
    AUTOEXP,   // Evlocallabsharcontrast
    AUTOEXP,   // EvLocenacontrast
    AUTOEXP,   // Evlocallablcradius
    AUTOEXP,   // Evlocallablcamount
    AUTOEXP,   // Evlocallablcdarkness
    AUTOEXP,   // Evlocallablclightness
    AUTOEXP,   // Evlocallabsensilc
    AUTOEXP,   // Evlocallabdehaz
    AUTOEXP,   // EvLocenasoft
    AUTOEXP,   // EvLocallabstreng
    AUTOEXP,   // EvLocallabsensisf
    AUTOEXP,   // Evlocallabsharblur
    AUTOEXP,   // EvLocenalabregion
    AUTOEXP,   // EvlocallabshowmaskMethod
    AUTOEXP,   // EvLocallabSpotSelectedWithMask
    AUTOEXP,   // EvlocallabCCmaskshape
    AUTOEXP,   // EvlocallabLLmaskshape
    AUTOEXP,   // EvlocallabCCmaskexpshape
    AUTOEXP,   // EvlocallabLLmaskexpshape
    AUTOEXP,   // EvlocallabHHmaskshape
    AUTOEXP,   // Evlocallabstructcol
    AUTOEXP,   // Evlocallabstructexp
    AUTOEXP,   // EvlocallabHHmaskexpshape
    AUTOEXP,   // Evlocallabblendmaskcol
    AUTOEXP,   // Evlocallabblendmaskexp
    AUTOEXP,   // Evlocallabblurexpde
    AUTOEXP,   // EvLocallabEnaColorMask
    AUTOEXP,   // EvLocallabEnaExpMask
    AUTOEXP,   // Evlocallabblurcolde
    AUTOEXP,   // Evlocallabinversex
    AUTOEXP,   // Evlocallabstructexclu
    AUTOEXP,   // Evlocallabexpchroma
    AUTOEXP,   // EvLocallabLabGridValue
    AUTOEXP,   // EvLocallabLabstrengthgrid
    AUTOEXP,   // EvLocallabgridMethod
    AUTOEXP,   // EvLocenashadhigh
    AUTOEXP,   // EvLocallabhighlights
    AUTOEXP,   // EvLocallabh_tonalwidth
    AUTOEXP,   // EvLocallabshadows
    AUTOEXP,   // EvLocallabs_tonalwidth
    AUTOEXP,   // EvLocallabsh_radius
    AUTOEXP,   // EvLocallabsensihs
    AUTOEXP,   // Evlocallabradmaskcol
    AUTOEXP,   // Evlocallabradmaskexp
    AUTOEXP,   // EvlocallabToolAdded
    AUTOEXP,   // EvlocallabCCmaskSHshape
    AUTOEXP,   // EvlocallabLLmaskSHshape
    AUTOEXP,   // EvlocallabHHmaskSHshape
    AUTOEXP,   // EvlocallabblendmaskSH
    AUTOEXP,   // EvLocallabEnaSHMask
    AUTOEXP,   // EvlocallabradmaskSH
    AUTOEXP,   // EvlocallabblurSHde
    AUTOEXP,   // Evlocallabinverssh
    AUTOEXP,   // EvLocallabSpotbalan
    AUTOEXP,   // EvLocallabchromaskexp
    AUTOEXP,   // EvLocallabgammaskexp
    AUTOEXP,   // EvLocallabslomaskexp
    AUTOEXP,   // EvLocallabsoftradiusexp
    AUTOEXP,   // EvLocallabchromaskcol
    AUTOEXP,   // EvLocallabgammaskcol
    AUTOEXP,   // EvLocallabslomaskcol
    AUTOEXP,   // EvLocallabchromaskSH
    AUTOEXP,   // EvLocallabgammaskSH
    AUTOEXP,   // EvLocallabslomaskSH
    AUTOEXP,   // EvLocallabsoftradiuscol
    AUTOEXP,   // EvLocallabsoftradiusret
    AUTOEXP,   // EvLocallabsoftradiuscb
    AUTOEXP,   // EvLocallabSpotTransitweak
    AUTOEXP,   // EvLocallabclarityml
    AUTOEXP,   // EvLocallabcontresid
    AUTOEXP,   // Evlocallabnoiselumf0
    AUTOEXP,   // Evlocallabnoiselumf2
    0,   // Evlocallabblurcbdl
    AUTOEXP,   // Evlocallabblendmaskcb
    AUTOEXP,   // Evlocallabradmaskcb
    AUTOEXP,   // Evlocallabchromaskcb
    AUTOEXP,   // Evlocallabgammaskcb
    AUTOEXP,   // Evlocallabslomaskcb
    AUTOEXP,   // EvlocallabCCmaskcbshape
    AUTOEXP,   // EvlocallabLLmaskcbshape
    AUTOEXP,   // EvlocallabHHmaskcbshape
    AUTOEXP,   // EvLocallabEnacbMask
    M_VOID,           // EvlocallabToolRemovedWithoutRefresh
    AUTOEXP,   // Evlocallabsoftradiustm
    AUTOEXP,   // EvLocallabSpotTransitgrad
    AUTOEXP,   // Evlocallabamount
    AUTOEXP,   // Evlocallabsatur
    AUTOEXP,   // EvlocallabCCmaskretishape
    AUTOEXP,   // EvlocallabLLmaskretishape
    AUTOEXP,   // EvlocallabHHmaskretishape
    AUTOEXP,   // EvLocallabEnaretiMask
    AUTOEXP,   // Evlocallabblendmaskreti
    AUTOEXP,   // Evlocallabradmaskreti
    AUTOEXP,   // Evlocallabchromaskreti
    AUTOEXP,   // Evlocallabgammaskreti
    AUTOEXP,   // Evlocallabslomaskreti
    AUTOEXP,   // EvlocallabToolRemovedWithRefresh
    AUTOEXP,   // EvLocallabEnaretiMasktmap
    AUTOEXP,   // Evlocallabscalereti
    AUTOEXP,   // Evlocallabdarkness
    AUTOEXP,   // Evlocallablightnessreti
    AUTOEXP,   // Evlocallablimd
    AUTOEXP,   // Evlocallablaplace
    AUTOEXP,   // EvlocallabsoftMethod
    AUTOEXP,   // Evlocallabequilret
    AUTOEXP,   // Evlocallabequiltm
    AUTOEXP,   // Evlocallabfftwlc
    AUTOEXP,   // Evlocallabfftwreti
    AUTOEXP,   // EvlocallabshowmasksoftMethod
    AUTOEXP,   // Evlocallabshadex
    AUTOEXP,   // EvlocallabexpMethod
    AUTOEXP,   // EvLocallablaplacexp
    AUTOEXP,   // EvLocallabbalanexp
    AUTOEXP,   // EvLocallablinear
    AUTOEXP,   // EvlocallabCCmasktmshape
    AUTOEXP,   // EvlocallabLLmasktmshape
    AUTOEXP,   // EvlocallabHHmasktmshape
    AUTOEXP,   // EvLocallabEnatmMask
    AUTOEXP,   // Evlocallabblendmasktm
    AUTOEXP,   // Evlocallabradmasktm
    AUTOEXP,   // Evlocallabchromasktm
    AUTOEXP,   // Evlocallabgammasktm
    AUTOEXP,   // Evlocallabslomasktm
    AUTOEXP,   // EvlocallabshowmasktmMethod
    AUTOEXP,   // EvlocallablocalcontMethod
    AUTOEXP,   // Evlocallabwavcurve
    AUTOEXP,   // Evlocallablevelwav
    AUTOEXP,   // Evlocallabresidcont
    AUTOEXP,   // EvlocallabCCmaskblshape
    AUTOEXP,   // EvlocallabLLmaskblshape
    AUTOEXP,   // EvlocallabHHmaskblshape
    AUTOEXP,   // EvLocallabEnablMask
    AUTOEXP,   // EvlocallabshowmaskblMethod
    AUTOEXP,   // Evlocallabblendmaskbl
    AUTOEXP,   // Evlocallabradmaskbl
    AUTOEXP,   // Evlocallabchromaskbl
    AUTOEXP,   // Evlocallabgammaskbl
    AUTOEXP,   // Evlocallabslomaskbl
    AUTOEXP,   // EvlocallabblMethod
    AUTOEXP,   // EvlocallabmedMethod
    AUTOEXP,   // Evlocallabitera
    AUTOEXP,   // Evlocallabguidbl
    AUTOEXP,   // Evlocallabepsbl
    AUTOEXP,   // EvlocallabshowmaskcolMethodinv
    AUTOEXP,   // EvlocallabshowmaskexpMethodinv
    AUTOEXP,   // EvlocallabshowmaskSHMethodinv
    AUTOEXP,   // Evlocallabclarilres
    AUTOEXP,   // Evlocallabclarisoft
    AUTOEXP,   // Evlocallabclaricres
    AUTOEXP,   // Evlocallabresidchro
    AUTOEXP,   // Evlocallabgamm
    AUTOEXP,   // Evlocallabfatamount
    AUTOEXP,   // Evlocallabfatdetail
    AUTOEXP,   // Evlocallabfatanchor
    AUTOEXP,   // Evlocallabfatlevel
    AUTOEXP,   // EvlocallabSpotCreated
    AUTOEXP,   // EvlocallabexnoiseMethod
    AUTOEXP,   // Evlocallabdepth
    AUTOEXP,   // Evlocallabloglin
    AUTOEXP,   // EvlocallabdehazeSaturation
    AUTOEXP,   // Evlocallaboffs
    AUTOEXP,   // EvlocallabCTtransCurve
    AUTOEXP,   // Evlocallabcliptm
    AUTOEXP,   // Evlocallabenatmmaskaft
    AUTOEXP,   // EvlocallabenaExpmaskaft
    AUTOEXP,   // Evlocallablapmasktm
    AUTOEXP,   // Evlocallablapmaskreti
    AUTOEXP,   // Evlocallablapmaskexp
    AUTOEXP,   // Evlocallablapmaskcol
    AUTOEXP,   // EvlocallablapmaskSH
    AUTOEXP,   // Evlocallablapmaskcb
    AUTOEXP,   // Evlocallablapmaskbl
    AUTOEXP,   // Evlocallablaplac
    AUTOEXP,   // Evlocallabdetailthr
    AUTOEXP,   // Evlocallabfftwbl
    AUTOEXP,   // Evlocallabisogr
    AUTOEXP,   // Evlocallabstrengr
    AUTOEXP,   // Evlocallabscalegr
    AUTOEXP,   // EvlocallabLmaskshape
    AUTOEXP,   // EvlocallabLmaskexpshape
    AUTOEXP,   // EvlocallabLmaskSHshape
    AUTOEXP,   // EvlocallabLmasktmshape
    AUTOEXP,   // EvlocallabLmaskretishape
    AUTOEXP,   // EvlocallabLmaskcbshape
    AUTOEXP,   // EvlocallabLmaskblshape
    AUTOEXP,   // EvlocallabLLmaskblshapewav
    AUTOEXP,   // Evlocallabshadmaskbl
    AUTOEXP,   // EvlocallabLLmaskcolshapewav
    AUTOEXP,   // Evlocallabshadmaskcol
    AUTOEXP,   // EvlocallabcsThreshold
    AUTOEXP,   // EvlocallabcsThresholdblur
    AUTOEXP,   // EvlocallabcsThresholdcol
    AUTOEXP,   // Evlocallabdeltae
    AUTOEXP,   // EvLocallabSpotscopemask
    AUTOEXP,   // EvlocallabshMethod
    AUTOEXP,   // EvlocallabEqualizersh
    AUTOEXP,   // EvlocallabdetailSH
    AUTOEXP,   // EvlocallabfatamountSH
    AUTOEXP,   // EvlocallabfatanchorSH
    AUTOEXP,   // Evlocallabshortc
    AUTOEXP,   // EvLocallabSpotlumask
    AUTOEXP,   // EvlocallabgamSH
    AUTOEXP,   // EvlocallabsloSH
    AUTOEXP,   // Evlocallabsavrest
    AUTOEXP,   // Evlocallabrecurs
    AUTOEXP,   // EvLocallabmergecolMethod
    AUTOEXP,   // EvLocallabopacol
    AUTOEXP,   // Evlocallabrgbshape
    AUTOEXP,   // EvLocallabtoneMethod
    AUTOEXP,   // EvLocallabspecial
    AUTOEXP,   // EvLocallabconthrcol
    AUTOEXP,   // EvLocallabmerMethod
    AUTOEXP,   // EvLocallabstrumaskcol
    AUTOEXP,   // EvLocallabstrumaskbl
    AUTOEXP,   // EvLocallabtoolcol
    AUTOEXP,   // Evlocallabtoolbl
    AUTOEXP,   // EvlocallabHHhmaskshape
    AUTOEXP,   // EvlocallabCCmaskvibshape
    AUTOEXP,   // EvlocallabLLmaskvibshape
    AUTOEXP,   // EvlocallabHHmaskvibshape
    AUTOEXP,   // EvlocallabshowmaskvibMethod
    AUTOEXP,   // EvLocallabEnavibMask
    AUTOEXP,   // Evlocallabblendmaskvi
    AUTOEXP,   // Evlocallabradmaskvib
    AUTOEXP,   // Evlocallabchromaskvib
    AUTOEXP,   // Evlocallabgammaskvib
    AUTOEXP,   // Evlocallabslomaskvib
    AUTOEXP,   // Evlocallablapmaskvib
    AUTOEXP,   // EvlocallabLmaskvibshape
    AUTOEXP,   // EvLocallabLabGridmergValue
    AUTOEXP,   // EvLocallabmercol
    AUTOEXP,   // EvLocallabmerlucol
    AUTOEXP,   // Evlocallabstrmaskexp
    AUTOEXP,   // Evlocallabangmaskexp
    AUTOEXP,   // Evlocallabstrexp
    AUTOEXP,   // Evlocallabangexp
    AUTOEXP,   // EvlocallabstrSH
    AUTOEXP,   // EvlocallabangSH
    AUTOEXP,   // Evlocallabstrcol
    AUTOEXP,   // Evlocallabangcol
    AUTOEXP,   // Evlocallabstrcolab
    AUTOEXP,   // EvLocallabSpotfeather
    AUTOEXP,   // Evlocallabstrcolh
    AUTOEXP,   // Evlocallabstrvib
    AUTOEXP,   // Evlocallabangvib
    AUTOEXP,   // Evlocallabstrvibab
    AUTOEXP,   // Evlocallabstrvibh
    AUTOEXP,   // EvLocallabSpotcomplexMethod
    AUTOEXP,   // Evlocallabclshape
    AUTOEXP,   // Evlocallablcshape
    AUTOEXP,   // Evlocallabblurcol
    AUTOEXP,   // Evlocallabcontcol
    AUTOEXP,   // EvLocallabfftColorMask
    RGBCURVE | M_AUTOEXP,   // EvLocenalog
    AUTOEXP,          // EvLocallabAuto
    AUTOEXP,   // EvlocallabsourceGray
    AUTOEXP,          // EvlocallabsourceGrayAuto
    AUTOEXP,          // EvlocallabAutoGray
    AUTOEXP,   // EvlocallabblackEv
    AUTOEXP,   // EvlocallabwhiteEv
    AUTOEXP,   // EvlocallabtargetGray
    AUTOEXP,   // Evlocallabdetail
    AUTOEXP,   // Evlocallabsensilog
    AUTOEXP,          // Evlocallabfullimage
    AUTOEXP,   // Evlocallabbaselog
    AUTOEXP,   // Evlocallabresidblur
    AUTOEXP,   // Evlocallabblurlc
    AUTOEXP,   // Evlocallablevelblur
    AUTOEXP,   // EvlocallabwavCurvelev
    AUTOEXP,   // EvlocallabwavCurvecon
    AUTOEXP,   // Evlocallabsigma
    AUTOEXP,   // Evlocallaboriglc
    AUTOEXP,   // Evlocallabsigmadc
    AUTOEXP,   // Evlocallabdeltad
    AUTOEXP,   // EvlocallabwavCurvecomp
    AUTOEXP,   // Evlocallabfatres
    AUTOEXP,   // EvLocallabSpotbalanh
    AUTOEXP,   // EvlocallabwavCurveden
    AUTOEXP,   // EvlocallabHHmasklcshape
    AUTOEXP,   // EvlocallabCCmasklcshape
    AUTOEXP,   // EvlocallabLLmasklcshape
    AUTOEXP,   // EvlocallabEnalcMask
    AUTOEXP,   // EvlocallabshowmasklcMethod
    AUTOEXP,   // Evlocallabblendmasklc
    AUTOEXP,   // Evlocallabradmasklc
    AUTOEXP,   // Evlocallabchromasklc
    AUTOEXP,   // EvlocallabLmasklcshape
    AUTOEXP,   // Evlocallabchromalev
    AUTOEXP,   // Evlocallabchromablu
    AUTOEXP,   // Evlocallaboffset
    AUTOEXP,   // Evlocallabwavblur
    AUTOEXP,   // Evlocallabwavcont
    AUTOEXP,   // Evlocallabwavcomp
    AUTOEXP,   // Evlocallabwavcompre
    AUTOEXP,   // EvlocallabwavCurvecompre
    AUTOEXP,   // Evlocallabresidcomp
    AUTOEXP,   // Evlocallabthreswav
    AUTOEXP,   // Evlocallabstrwav
    AUTOEXP,   // Evlocallabangwav
    AUTOEXP,   // Evlocallabwavgradl
    AUTOEXP,   // Evlocallabstrlog
    AUTOEXP,   // Evlocallabanglog
    AUTOEXP,   // EvLocallabSpotcolorde
    AUTOEXP,   // EvlocallabshowmasksharMethod
    AUTOEXP,   // Evlocallabshowreset
    AUTOEXP,   // Evlocallabstrengthw
    AUTOEXP,   // Evlocallabradiusw
    AUTOEXP,   // Evlocallabdetailw
    AUTOEXP,   // Evlocallabgradw
    AUTOEXP,   // Evlocallabtloww
    AUTOEXP,   // Evlocallabthigw
    AUTOEXP,   // EvlocallabwavCurveedg
    AUTOEXP,   // EvlocallablocaledgMethod
    AUTOEXP,   // Evlocallabwavedg
    AUTOEXP,   // Evlocallabedgw
    AUTOEXP,   // Evlocallabbasew
    AUTOEXP,   // EvlocallablocalneiMethod
    AUTOEXP,   // Evlocallabwaveshow
    AUTOEXP,   // EvLocallabSpotwavMethod
    AUTOEXP,   // EvlocallabchroMethod
    AUTOEXP,   // Evlocallabstrbl
    AUTOEXP,   // Evlocallabsigmadr
    AUTOEXP,   // Evlocallabsigmabl
    AUTOEXP,   // Evlocallabsigmaed
    AUTOEXP,   // Evlocallabresidsha
    AUTOEXP,   // Evlocallabresidshathr
    AUTOEXP,   // Evlocallabresidhi
    AUTOEXP,   // Evlocallabresidhithr
    AUTOEXP,   // Evlocallabsigmalc
    AUTOEXP,   // Evlocallabsigmalc2
    AUTOEXP,   // Evlocallabblwh
    AUTOEXP,   // EvlocallabcomplexityWithRefresh
    0,                // can be reused
    AUTOEXP,   // EvLocallabSpotcolorscope
    AUTOEXP,   // EvlocallabshowmasktypMethod
    AUTOEXP,   // Evlocallabshadmaskblsha
    AUTOEXP,   // EvLocenamask
    AUTOEXP,   // Evlocallabsensimask
    AUTOEXP,   // Evlocallabblendmask
    AUTOEXP,   // EvLocallabEna_Mask
    AUTOEXP,   // Evlocallabradmask
    AUTOEXP,   // Evlocallablapmask
    AUTOEXP,   // Evlocallabchromask
    AUTOEXP,   // Evlocallabgammask
    AUTOEXP,   // Evlocallabslopmask
    AUTOEXP,   // EvlocallabCCmask_shape
    AUTOEXP,   // EvlocallabLLmask_shape
    AUTOEXP,   // EvlocallabHHmask_shape
    AUTOEXP,   // EvLocallabtoolmask
    AUTOEXP,   // Evlocallabstrumaskmask
    AUTOEXP,   // EvlocallabHHhmask_shape
    AUTOEXP,   // EvLocallabfftmask
    AUTOEXP,   // Evlocallabblurmask
    AUTOEXP,   // Evlocallabcontmask
    AUTOEXP,   // Evlocallabshadmask
    AUTOEXP,   // EvlocallabLmask_shape
    AUTOEXP,   // EvlocallabLLmask_shapewav
    AUTOEXP,   // EvlocallabcsThresholdmask
    AUTOEXP,   // Evlocallabstr_mask
    AUTOEXP,   // Evlocallabang_mask
    AUTOEXP,   // Evlocallabsoftradiusmask
    AUTOEXP,   // Evlocallabblendmaskab
    AUTOEXP,   // EvLocallabSpotprevMethod
    AUTOEXP,   // Evlocallabactiv
    AUTOEXP,   // EvlocallabCHshape
    AUTOEXP,   //EvlocallabquaMethod
    AUTOEXP,   //Evlocallabhishow
    AUTOEXP,   // Evlocallabinvbl
    AUTOEXP,   // Evlocallabcatad
    AUTOEXP,   // Evlocallabciecam
    AUTOEXP,   // Evlocallabsourceabs
    AUTOEXP,   // Evlocallabtargabs
    AUTOEXP,   // Evlocallabsurround
    AUTOEXP,   // Evlocallabsaturl
    AUTOEXP,   // Evlocallabcontl
    AUTOEXP,   //EvlocallabCCmaskshapeL 
    AUTOEXP,   //EvlocallabLLmaskshapeL
    AUTOEXP,   // EvlocallabHHmaskshapeL
    AUTOEXP,   // EvlocallabenaLMask
    AUTOEXP,   // EvlocallabblendmaskL
    AUTOEXP,   // EvlocallabradmaskL
    AUTOEXP,   // EvlocallabchromaskL
    AUTOEXP,   //EvlocallabLmaskshapeL
    AUTOEXP,   // Evlocallablightl
    AUTOEXP,   // EvlocallabLshapeL
    AUTOEXP,   // Evlocallabcontq
    AUTOEXP,   // Evlocallabsursour
    AUTOEXP,   // Evlocallablightq
    AUTOEXP,   // Evlocallabcolorfl
    AUTOEXP,   // Evlocallabrepar
    AUTOEXP,   //EvlocallabwavCurvehue
    AUTOEXP,   // Evlocallablevelthr
    AUTOEXP,   // Evlocallablevelthrlow
    AUTOEXP,   //Evlocallabusemask1
    AUTOEXP,   // Evlocallablnoiselow
    AUTOEXP,   // Evlocallabrecothres
    AUTOEXP,   // Evlocallablowthres
    AUTOEXP,   // Evlocallabhigthres
    AUTOEXP,   // Evlocallabrecothresd
    AUTOEXP,   // Evlocallablowthresd
    AUTOEXP,   // Evlocallabhigthresd
    AUTOEXP,   // Evlocallabinvmaskd
    AUTOEXP,   // Evlocallabinvmask
    AUTOEXP,   // Evlocallabdecayd
    AUTOEXP,   // Evlocallabrecothresc
    AUTOEXP,   // Evlocallablowthresc
    AUTOEXP,   // Evlocallabhigthresc
    AUTOEXP,   // Evlocallabdecayc
    AUTOEXP,   // Evlocallabmidthresd
    AUTOEXP,   // Evlocallabrecothresl
    AUTOEXP,   // Evlocallablowthresl
    AUTOEXP,   // Evlocallabhigthresl
    AUTOEXP,  // Evlocallabdecayl
    AUTOEXP,   // Evlocallabrecothrese
    AUTOEXP,   // Evlocallablowthrese
    AUTOEXP,   // Evlocallabhigthrese
    AUTOEXP,   // Evlocallabdecaye
    AUTOEXP,   // Evlocallabrecothress
    AUTOEXP,   // Evlocallablowthress
    AUTOEXP,   // Evlocallabhigthress
    AUTOEXP,   // Evlocallabdecays
    AUTOEXP,   // Evlocallabrecothrev
    AUTOEXP,   // Evlocallablowthresv
    AUTOEXP,   // Evlocallabhigthresv
    AUTOEXP,   // Evlocallabdecayv
    AUTOEXP,   // Evlocallabrecothrew
    AUTOEXP,   // Evlocallablowthresw
    AUTOEXP,   // Evlocallabhigthresw
    AUTOEXP,   // Evlocallabdecayw
    AUTOEXP,   // Evlocallabmidthresdch
    AUTOEXP,   // Evlocallabrecothret
    AUTOEXP,   // Evlocallablowthrest
    AUTOEXP,   // Evlocallabhigthrest
    AUTOEXP,   // Evlocallabdecayt
    AUTOEXP,   // Evlocallabrecothrecb
    AUTOEXP,   // Evlocallablowthrescb
    AUTOEXP,   // Evlocallabhigthrescb
    AUTOEXP,   // Evlocallabdecaycb
    AUTOEXP,   // Evlocallabrecothrer
    AUTOEXP,   // Evlocallablowthresr
    AUTOEXP,   // Evlocallabhigthresr
    AUTOEXP   // Evlocallabdecayr


};


namespace rtengine
{

RefreshMapper::RefreshMapper():
    next_event_(rtengine::NUMOFEVENTS)
{
    for (int event = 0; event < rtengine::NUMOFEVENTS; ++event) {
        actions_[event] = refreshmap[event];
    }
}


ProcEvent RefreshMapper::newEvent()
{
    return ProcEvent(++next_event_);
}


void RefreshMapper::mapEvent(ProcEvent event, int action)
{
    actions_[event] = action;
}


int RefreshMapper::getAction(ProcEvent event) const
{
    auto it = actions_.find(event);

    if (it == actions_.end()) {
        return 0;
    } else {
        return it->second;
    }
}


RefreshMapper *RefreshMapper::getInstance()
{
    static RefreshMapper instance;
    return &instance;
}

} // namespace rtengine
