[Icon Theme]
Name=RawTherapee-Dark
Comment=Dark theme for RawTherapee
Inherits=hicolor
Example=folder

Directories=actions,apps,categories,devices,emblems,places,status

[actions]
Size=22
Context=Actions
Type=Fixed

[apps]
Size=22
Context=Applications
Type=Fixed

[categories]
Size=22
Context=Categories
Type=Fixed

[devices]
Size=22
Context=Devices
Type=Fixed

[emblems]
Size=22
Context=Emblems
Type=Fixed

[places]
Size=22
Context=Places
Type=Fixed

[status]
Size=22
Context=Status
Type=Fixed
