#ifndef _ADDSETIDS_
#define _ADDSETIDS_

#define ADDSET_TC_EXPCOMP 		0
#define ADDSET_TC_BRIGHTNESS 	1
#define ADDSET_TC_BLACKLEVEL 	2
#define ADDSET_TC_CONTRAST 		3
#define ADDSET_SH_HIGHLIGHTS 	4
#define ADDSET_SH_SHADOWS 		5
#define ADDSET_SH_LOCALCONTRAST 6
#define ADDSET_LC_BRIGHTNESS 	7
#define ADDSET_LC_CONTRAST 		8
#define ADDSET_SHARP_AMOUNT 	9
#define ADDSET_LD_EDGETOLERANCE 10
#define ADDSET_WB_TEMPERATURE 	11
#define ADDSET_WB_GREEN 		12
#define ADDSET_CBOOST_AMOUNT 	13
#define ADDSET_CS_BLUEYELLOW 	14
#define ADDSET_CS_GREENMAGENTA 	15
#define ADDSET_ROTATE_DEGREE 	16
#define ADDSET_DIST_AMOUNT 		17
#define ADDSET_PERSPECTIVE		18
#define ADDSET_CA	 			19
#define ADDSET_VIGN_AMOUNT 		20
#define ADDSET_LC_SATURATION 	21
#define ADDSET_TC_SATURATION 	22

#define ADDSET_TC_HLCOMPAMOUNT 	23
#define ADDSET_TC_HLCOMPTHRESH 	24
#define ADDSET_TC_SHCOMP 	    25
// When adding items, make sure to update ADDSET_PARAM_NUM
#define ADDSET_PARAM_NUM		26 // THIS IS USED AS A DELIMITER!!


#endif
