#ifndef _ADDSETIDS_
#define _ADDSETIDS_


//          UPDATE THE DEFAULT VALUE IN OPTIONS.CC TOO !!!


#define ADDSET_TC_EXPCOMP		0
#define ADDSET_TC_BRIGHTNESS	1
#define ADDSET_TC_BLACKLEVEL	2
#define ADDSET_TC_CONTRAST		3
#define ADDSET_SH_HIGHLIGHTS	4
#define ADDSET_SH_SHADOWS		5
#define ADDSET_SH_LOCALCONTRAST	6
#define ADDSET_LC_BRIGHTNESS	7
#define ADDSET_LC_CONTRAST		8
#define ADDSET_SHARP_AMOUNT		9
#define ADDSET_LD_EDGETOLERANCE 10
#define ADDSET_WB_TEMPERATURE	11
#define ADDSET_WB_GREEN			12
#define ADDSET_CBOOST_AMOUNT	13
#define ADDSET_CS_BLUEYELLOW	14
#define ADDSET_CS_GREENMAGENTA	15
#define ADDSET_ROTATE_DEGREE	16
#define ADDSET_DIST_AMOUNT		17
#define ADDSET_PERSPECTIVE		18
#define ADDSET_CA				19
#define ADDSET_VIGN_AMOUNT		20
#define ADDSET_LC_SATURATION	21
#define ADDSET_TC_SATURATION	22
#define ADDSET_TC_HLCOMPAMOUNT	23
#define ADDSET_TC_HLCOMPTHRESH	24
#define ADDSET_TC_SHCOMP		25

#define ADDSET_DIRPYREQ			26
#define ADDSET_DIRPYRDN_CHLUM	27
#define ADDSET_DIRPYRDN_GAMMA	28
#define ADDSET_CHMIXER			29

#define ADDSET_PREPROCESS_GREENEQUIL	30
#define ADDSET_PREPROCESS_LINEDENOISE	31
#define ADDSET_RAWCACORR				32
#define ADDSET_RAWEXPOS_LINEAR			33
#define ADDSET_RAWEXPOS_PRESER			34
#define ADDSET_RAWEXPOS_BLACKS			35
#define ADDSET_SHARPENEDGE_AMOUNT		36
#define ADDSET_SHARPENMICRO_AMOUNT		37
#define ADDSET_SHARPENEDGE_PASS			38
#define ADDSET_SHARPENMICRO_UNIFORMITY	39
#define ADDSET_VIBRANCE_PASTELS			40
#define ADDSET_VIBRANCE_SATURATED		41
#define ADDSET_FREE_OUPUT_GAMMA			42
#define ADDSET_FREE_OUTPUT_SLOPE		43

// When adding items, make sure to update ADDSET_PARAM_NUM
#define ADDSET_PARAM_NUM		44 // THIS IS USED AS A DELIMITER!!

#endif
