// This file is automatically generated by the Makefile ; DO NOT EDIT!
// You can (should) also tell mercurial to ignore it.

#ifndef _VERSION_
#define _VERSION_

#define VERSION "release-3.0-a1.651"
#define TAGDISTANCE 651

#endif
