// This file is automatically generated by the Makefile - DO NOT EDIT!
// You can (should) also tell mercurial to ignore it.

#ifndef _VERSION_
#define _VERSION_

#define VERSION "Dev-Float.63"
#define TAGDISTANCE 63

#endif

